# Setup
title:        "Hao's Blog"
tagline:      Programming | Thoughts | Life
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Hao Chen
  url:        http://haoc.io 

# Gems
gems:
  - jekyll-paginate

#Others
# markdown: redcarpet
markdown: kramdown 
